### ISSUE TITLE
Error Message at the top of Main Control Panel

### ISSUE THREAD

**Issue by DeannaCaracciolo** [orcoastalmgmt/ooi#1]
I assume this is just another one of those weird server things.  Just just in case-

Message Reads:
Error
We have detected that your server is using PHP 5.6.40 which is obsolete and no longer receives official security updates by its developers. The Joomla! Project recommends upgrading your site to PHP 7.2 or later which will receive security updates at least until 2020-11-30. Please ask your host to make PHP 7.2 or a later version the default version for your site. If your host is already PHP 7.2 ready please enable PHP 7.2 on your site's root and 'administrator' directories – typically you can do this yourself through a tool in your hosting control panel, but it's best to ask your host if you are unsure.

**Comment by tchaddad** [comment]
This is resolved on the new server so I am closing this issue here. The new server will be up soon, I swear!
